# Generated by Django 2.2 on 2020-02-15 09:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports_type', models.CharField(choices=[('football', 'Football'), ('cricket', 'Cricket'), ('badminton', 'Badminton'), ('karate', 'Karate'), ('table tennis', 'Table Tennis'), ('gymnastics', 'Gymnastics'), ('boxing', 'Boxing'), ('chess', 'Chess'), ('volleyball', 'Volleyball'), ('basketball', 'Basketball'), ('e gaming', 'E Gaming'), ('swimming', 'Swimming')], default='football', max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=255)),
                ('featured_Image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
